-- Schema alignment patch for BACKEND_SPEC_V3_4
ALTER TABLE properties
  ADD COLUMN IF NOT EXISTS currency VARCHAR(10) NOT NULL DEFAULT 'TL' AFTER price,
  ADD COLUMN IF NOT EXISTS total_floors INT NULL AFTER floor_location,
  ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL AFTER updated_at;

ALTER TABLE advisors
  ADD COLUMN IF NOT EXISTS is_founder TINYINT(1) NOT NULL DEFAULT 0 AFTER total_sales,
  ADD COLUMN IF NOT EXISTS title VARCHAR(255) NULL AFTER is_founder;

CREATE TABLE IF NOT EXISTS site_settings (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  setting_key VARCHAR(190) NOT NULL UNIQUE,
  setting_value TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
